### ISSUE TITLE
TLS ciphers and protocol for backend connection

### ISSUE THREAD

**Issue by dieti80** [libuweber/microgateway#12]
Allow to configure the following settings:

\# (Context: global, back-end group)
\#
\# Set the back-end SSL protocol version:
\# DEFAULT, SSLv3, TLSv1.0, TLSv1.1, TLSv1.2, TLSv1.3, TLSv1.x
\# Note: TLSv1 is a legacy value with the same meaning as TLSv1.0
BackendSSLVersion                                 "DEFAULT"

\# Set the back-end SSL cipher list (up to TLS 1.2)
\# For documentation visit www.openssl.org and search for "ciphers"
BackendSSLCipherSuite                             "DEFAULT"

\# Set the back-end SSL cipher list (TLS 1.3)
\# The default cipher list is used if this setting is the empty string.
\# For documentation visit www.openssl.org and search for "ciphers"
BackendSSLCipherSuiteTls13                        ""

**Comment by jubeergon** [comment]
@dieti80 
Should I implement version 1 or 2 here?
Or do you see another solution.
1) Two possible settings, same as in the SG. 
        # config.default.backend.tls.CipherSuite --  Set the back-end SSL cipher list (up to TLS 1.2)
        CipherSuite: ""
        # config.default.backend.tls.CipherSuiteTls13 -- Set the back-end SSL cipher list (TLS 1.3)
        CipherSuiteTls13: "" 

2) One Setting with a Logic. 
 # config.default.backend.tls.CipherSuite --  Set the back-end SSL cipher list
        CipherSuite: ""

{{- if eq $config.default.backend.tls.Version "TLSv1.3" }}
        BackendSSLCipherSuiteTls13 ""  {{ $config.default.backend.tls.CipherSuite }}
{{- else }}
       BackendSSLCipherSuite ""  {{ $config.default.backend.tls.CipherSuite }}
{{- end }}
