### ISSUE TITLE
Naming: Use "hostname" instead of "service"

### ISSUE THREAD

**Issue by dieti80** [libuweber/microgateway#13]
https://github.com/libuweber/microgateway/blob/739d532274d765410df946f2897457ec64817d7c/charts/microgateway/templates/configmap.yaml#L49

Use the same key for "hostname". 

Change "service" to "hostname" (in the variable).

**Comment by jubeergon** [comment]
Fixed. 
mirogateway Version: 0.3.5
commit bea6a5979dab410cff6cf467475204883332f884 

README changes
commit b5f9fae05dbdce12667e2f6b098d37a647a27f78
