### ISSUE TITLE
Better solution for configuring chart name

### ISSUE THREAD

**Issue by dieti80** [libuweber/microgateway#25]
https://github.com/libuweber/microgateway/blob/5ddf85a2e2cfba0e91849766e05279dae83d40de/.github/helm-docs-generate.sh#L14

Create a variable on the top of the script and set the chart name to "microgateway" or try to get the chart name from a variable.

**Comment by jubeergon** [comment]
The helm-docs-generated script should become generic. 
If possible read the variables like ${BRANCH_NAME} from the pipeline and pass them to the script. 
Otherwise use a variable at the beginning of the script.

**Comment by jubeergon** [comment]
Fixed in airlock-helm-charts Repo.
