### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by jubeergon** [libuweber/microgateway#26]
Document how to use Ingess/Route. 
With & without tls. 
```
annotations:
  kubernetes.io/ingress.class: 
  nginx.ingress.kubernetes.io/rewrite-target: / 
```

**Comment by dieti80** [comment]
The following topics should also be addressed by the README:
* Security: Hardening
* Simple example (use only the basic switches)
* Advanced example (configure own apps)
** Mention, that the default switches (IPHeader, VH Cipher, ... ) still work
* Expert example (configure the whole DSL)
** Mention, that the other switches cannot be used anymore or do not work.
* Example for a secret with SSL Certs (eventually also how to create them)
* How to set environment variables which could be used in the DSL (short example)
* Liveness and Readiness Probe
** Mention if, when and how to adapt it
* If possible, change the order of the values (manual order or exactly the way it is in values.yaml). I don't know whether there is a parameter to allow different kind of order.
