### ISSUE TITLE
NOTES.txt

### ISSUE THREAD

**Issue by dieti80** [libuweber/microgateway#4]
Improve NOTES.txt

**Comment by jubeergon** [comment]
Done:
* Network configuration
ToDo:
* Redis configuration
* WAF Pods
  * Show available Pods
  * Show Pods Logs
  * Access Pod (Bash)

**Comment by jubeergon** [comment]
* External connectivity
* ConfigMap
* Microgateway Pods
* Microgateway Logs
* Microgateway Console
