### ISSUE TITLE
Only configure RemoteIPHeader if trusted IPs are configured

### ISSUE THREAD

**Issue by dieti80** [libuweber/microgateway#7]
https://github.com/libuweber/microgateway/blob/739d532274d765410df946f2897457ec64817d7c/charts/microgateway/templates/configmap.yaml#L24

This should only be configured if trusted IPs are configured

**Comment by jubeergon** [comment]
QA: 
No expert settings: OK
Just SG: OK
Just Apache: OK
Just IPHeader: OK
Apache & IPHeader: OK
SG & IPHeader: OK
SG & Apache: Ok
SG & Apache & IPHeader: OK
